### ISSUE TITLE
add an optional shape

### ISSUE THREAD

**Issue by electrovir** [electrovir/object-shape-tester#2]
Right now you can accomplish potentially undefined properties by using `or(undefined , '')`, for example. However, this does not allow the property to be optionally _entirely missing_.

Proposal:

```typescript
defineShape({
    potentiallyUndefined: or('', undefined),
    potentiallyMissing: optional(or('', undefined)),
});
```

or maybe

```typescript
defineShape(and({
    potentiallyUndefined: or('', undefined),
}, partial({
    potentiallyMissing: optional(or('', undefined)),
})));
```

`partial` will probably be much easier as it only needs to affect its children rather than `optional` while will need to affect its parent.

**Comment by KylerHansen** [comment]
Is this also what you were thinking?
defineShape({
    item: optional(' '),
    count: optional(4),
    authLevel: optional(enumShape(AuthLevel)),
});

**Comment by electrovir** [comment]
@KylerHansen: exactly, that'd be the first example. That'd be optimal for the usage experience, but the internal implementation might be too complex for TypeScript to handle.
